# Development environment values. Secrets are provisioned outside GitOps.
namespace: timeyou-dev

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

images:
  frontend:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-frontend
    digest: sha256:0f5145fb31589033c9c6b0449e826f07481c803de43a53542db71a6a4f8deda8
    pullPolicy: IfNotPresent
  focus:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-focus
    digest: sha256:4537ebd5486fd17533ba205393a4dac8ef359be214943587e0598fcead76c5d0
    pullPolicy: IfNotPresent
  analytics:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-analytics
    digest: sha256:6ec30f85993b4990d0c8ac90a7f40553b882446620b683647ac348874d878e0f
    pullPolicy: IfNotPresent

cognito:
  region: eu-west-1
  userPoolId: eu-west-1_ugZvDaE2i
  appClientId: 2oruncf8gbi07qo3tto7auuent
  issuer: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ugZvDaE2i
  redirectUri: http://localhost:3001/auth/callback
  logoutUri: http://localhost:3001

frontend:
  apiBaseUrl: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com/focus
  analyticsApiBaseUrl: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /

focus:
  corsOrigin: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /health

analytics:
  corsOrigin: http://localhost:3001
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /health

existingSecret:
  name: timeyou-runtime
