# Development environment values. Secrets are provisioned outside GitOps.
namespace: timeyou-dev

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'

images:
  frontend:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-frontend
    digest: sha256:c31d5c20866860a957882a077ee935bbd0c3bac1bf9b3e6cde6579d020ab3dc8
    pullPolicy: IfNotPresent
  focus:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-focus
    digest: sha256:d5022aded454bc4da06449ebef56d1a08ea7d84cb92ef6f0e2a1eecc93044215
    pullPolicy: IfNotPresent
  analytics:
    repository: 109678733855.dkr.ecr.eu-west-1.amazonaws.com/timeyou-analytics
    digest: sha256:2ea73b8872630bd48205e5600dd22638e11ab0f9dbc4b78236a3591d2e33545a
    pullPolicy: IfNotPresent

cognito:
  region: eu-west-1
  userPoolId: eu-west-1_ugZvDaE2i
  appClientId: 2oruncf8gbi07qo3tto7auuent
  issuer: https://cognito-idp.eu-west-1.amazonaws.com/eu-west-1_ugZvDaE2i
  redirectUri: http://localhost:3001/auth/callback
  logoutUri: http://localhost:3001

frontend:
  apiBaseUrl: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com/focus
  analyticsApiBaseUrl: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /

focus:
  corsOrigin: http://k8s-timeyoud-timeyou-2dcc5ce42f-789434591.eu-west-1.elb.amazonaws.com
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /health

analytics:
  corsOrigin: http://localhost:3001
  service:
    annotations:
      alb.ingress.kubernetes.io/healthcheck-path: /health

existingSecret:
  name: timeyou-runtime
