apiVersion: v1
kind: Service
metadata:
  name: {{ include "timeyou.fullname" . }}-analytics
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "timeyou.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
  {{- with .Values.analytics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "timeyou.name" . }}
    app.kubernetes.io/component: analytics
  ports:
    - name: http
      port: {{ .Values.analytics.service.port }}
      targetPort: http
