{{- if .Values.focus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "timeyou.fullname" . }}-focus
  namespace: {{ .Values.namespace }}
  labels:
    release: kube-prometheus-stack
    {{- include "timeyou.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "timeyou.name" . }}
      app.kubernetes.io/component: focus
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.focus.serviceMonitor.interval }}
{{- end }}
