apiVersion: v1
kind: Service
metadata:
  name: {{ include "timeyou.fullname" . }}-focus
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "timeyou.labels" . | nindent 4 }}
    app.kubernetes.io/component: focus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "timeyou.name" . }}
    app.kubernetes.io/component: focus
  ports:
    - name: http
      port: {{ .Values.focus.service.port }}
      targetPort: http
