apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeyou-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/frkndmr7/timeyou.git
    targetRevision: main
    path: deploy/charts/timeyou
    helm:
      valueFiles:
        - ../../environments/staging/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: timeyou-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
